### PR TITLE
Some tests for Nonpositive cone

### PR DESCRIPTION
**Pull request by AKS1996**
Good to find that MOSD is compatible with Nonpositives :D

### CODE REVIEW

**Comment by matbesancon** [comment]
thanks for the tests! I have no idea what makes Julia 1.0 complain again. I'm trying to bump FiniteDifferences to 0.12

**Comment by matbesancon** [comment]
Ah you opened the PR from the fork master. Could you change the version of FiniteDifferences to v0.11?

**Comment by matbesancon** [comment]
bump @AKS1996

**Comment by matbesancon** [comment]
bump @AKS1996

**Comment by AKS1996** [comment]
Changing it

**Pull request merged**
