### PR TITLE
Add projection to scaled set

### PR DESCRIPTION
**Pull request by blegat**
Needed for https://github.com/blegat/Zaphod.jl/pull/1

### CODE REVIEW

**Comment by blegat** [comment]
@matbesancon The failure in ci seems unrelated, it this a known issue ?

**Comment by matbesancon** [comment]
no this was not breaking before, from one of the latest MOI releases I assume?
It seems unhappy about a SAF getting a constant term

**Comment by matbesancon** [comment]
what did you change to make it work?

**Comment by blegat** [comment]
I fixed it in https://github.com/matbesancon/MathOptSetDistances.jl/pull/72 and rebased this PR on top of master after merging it

**Comment by blegat** [comment]
@matbesancon good to merge ?

**Comment by matbesancon** [comment]
yes thanks !

**Pull request merged**
